[package]
name = "diligent-date-parser"
version = "0.1.0"
authors = ["Andrey Kutejko <andy128k@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["date", "datetime", "parser", "parsing"]

[dependencies]
chrono = "0.4"
